title: AFTRLGHT -- Dallas Pop Band with Raw Emotion & Haunting Alt-Pop Sound
email: admin@aftrlght.com
url: "http://aftrlght.com"
base_path: ""

markdown: kramdown
plugins:
  - jekyll-coffeescript

sass:
  load_paths:
    - css
    - _lib
  style: compressed
