title: Animus -- High-energy hard rock band from Dallas, TX
email: admin@animusofficial.com
url: "http://animusofficial.com"
base_path: ""

markdown: kramdown
plugins:
  - jekyll-coffeescript

sass:
  load_paths:
    - css
    - _lib
  style: compressed
